server {
    listen 80;
    client_max_body_size 10M;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $api_upstream api:8000;
        proxy_pass http://$api_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        set $static_upstream static:80;
        proxy_pass http://$static_upstream;
    }
}